-- MySQL Script generated by MySQL Workbench
-- Sun Nov 17 23:57:49 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USER` (
  `FName` VARCHAR(10) NOT NULL,
  `MName` VARCHAR(10) NOT NULL,
  `LFName` VARCHAR(10) NOT NULL,
  `Phone_Number` INT NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Password` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passenger` (
  `FName` VARCHAR(45) NULL,
  `MName` VARCHAR(45) NULL,
  `LFName` VARCHAR(45) NULL,
  `PED` date NOT NULL,
  `BirthDate` date NOT NULL,
  `Ptid/Nid` INT NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Ptid/Nid`),
  INDEX `Email_idx` (`Email` ASC) VISIBLE,
  CONSTRAINT `Email`
    FOREIGN KEY (`Email`)
    REFERENCES `mydb`.`USER` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airline_Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airline_Company` (
  `Name` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NULL,
  `Airline_Com_ID` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Airline_Com_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TICKET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TICKET` (
  `Destination` VARCHAR(45) NOT NULL,
  `Departure` VARCHAR(45) NOT NULL,
  `Price` VARCHAR(45) NOT NULL,
  `TicketID` VARCHAR(10) NOT NULL,
  `Luggage_ID` VARCHAR(10) NULL,
  `Airline_Com_ID` VARCHAR(10) NOT NULL,
  `Year` INT(4) NOT NULL,
  `Month` INT(2) NOT NULL,
  `Day` INT(2) NOT NULL,
  `TIME` VARCHAR(5) NOT NULL,
  `Ptid/Nid` INT NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`TicketID`),
  UNIQUE INDEX `Luggage_ID_UNIQUE` (`Luggage_ID` ASC) VISIBLE,
  UNIQUE INDEX `Ptid/Nid_UNIQUE` (`Ptid/Nid` ASC) VISIBLE,
  INDEX `Email_idx` (`Email` ASC) VISIBLE,
  INDEX `Airline_Com_ID_idx` (`Airline_Com_ID` ASC) VISIBLE,
  CONSTRAINT `Luggage_ID`
    FOREIGN KEY (`Luggage_ID`)
    REFERENCES `mydb`.`LUGGAGE` (`Luggage_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Airline_Com_ID`
    FOREIGN KEY (`Airline_Com_ID`)
    REFERENCES `mydb`.`Airline_Company` (`Airline_Com_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Ptid/Nid`
    FOREIGN KEY (`Ptid/Nid`)
    REFERENCES `mydb`.`Passenger` (`Ptid/Nid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Email`
    FOREIGN KEY (`Email`)
    REFERENCES `mydb`.`USER` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LUGGAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LUGGAGE` (
  `Type` VARCHAR(45) NULL,
  `Weight` INT(2) NULL,
  `TicketID` VARCHAR(45) NOT NULL,
  `Luggage_ID` VARCHAR(10) NOT NULL,
  UNIQUE INDEX `TicketID_UNIQUE` (`TicketID` ASC) VISIBLE,
  PRIMARY KEY (`Luggage_ID`),
  CONSTRAINT `TicketID`
    FOREIGN KEY (`TicketID`)
    REFERENCES `mydb`.`TICKET` (`TicketID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAYMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PAYMENT` (
  `Card_Name` VARCHAR(45) NOT NULL,
  `CVV` INT(3) NOT NULL,
  `Year` INT(2) NOT NULL,
  `month` INT(2) NOT NULL,
  `Card_Number` INT(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Card_Number`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  CONSTRAINT `Email`
    FOREIGN KEY (`Email`)
    REFERENCES `mydb`.`USER` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TIC_Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIC_Class` (
  `Travel_Class` VARCHAR(15) NOT NULL,
  `TicketID` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Travel_Class`, `TicketID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DISCOUNT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DISCOUNT` (
  `User_ID` VARCHAR(10) NOT NULL,
  `CN/LN` VARCHAR(45) NOT NULL,
  `Scale` INT(2) NULL,
  `Email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`User_ID`, `Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pay` (
  `Card_Number` INT(45) NOT NULL,
  `TicketID` VARCHAR(10) NOT NULL,
  `Luggage_ID` VARCHAR(10)  NULL,
  PRIMARY KEY (`Card_Number`, `TicketID`, `Luggage_ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
